version: "3.7"

services:
  mysql:
    image: library/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=simple-app
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=Europe/Paris
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
  serv:
    build:
      context: ./docker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql
volumes:
  persistent: